name: Chess Setup

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: List contents of running directory
      run: dir
    - name: Build
      run: g++ buildWorkflow.cpp -o b.exe
    - name: List contents of running directory
      run: dir
    - name: Setup-Build
      run: |
        cmd
        g++ -Isrc/include -c main.cpp
        move "src" "Builds"
        xcopy icon.res Builds
        xcopy main.o Builds
        dir
        cd Builds
        dir
        g++ -m32 main.o -o main -L "src/lib" -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system icon.res
        del main.o
    - name: List contents of running directory
      run: dir
    - name: Run
      run: .\main.exe
