name: Chess Setup

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Change dir
      run: cd Chess
    - name: Build
      run: g++ buildWorkflow.cpp -o b.exe
    - name: Setup-Build
      run: b.exe main
    - name: Run
      run: cd Builds && main.exe
#   setup-build:
#     runs-on: windows-latest
#     steps:
#     - run: g++ build.cpp -o build.exe
#   setup:
#     needs: setup-build
#     runs-on: windows-latest
#     steps:
#     - run: build.exe main.cpp
#             xcopy .\main.exe .\Builds\main.exe /c
#   build:
#     needs: setup
#     runs-on: windows-latest
#     steps:
#     - run: .\Builds\main.exe
#   confirm:
#     needs: build
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
