name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "First issue always gives a great pleasure to open, thanks for reporting"
        pr-message: 'First PR request? Nervous? No worries, and, thanks for contributing'
